'''Crie um sistema de cadastro de usuário que registre as informações de “nome, sexo, endereço, cidade, estado, CEP, telefone, data de nascimento, RG, nome do pai, nome da mãe e grau de escolaridade” do usuário.

O sistema deve exibir as informações do usuário em um texto amigável.
'''
nome = input('Digite o seu Nome: ')
sexo = input('Digite o seu sexo: ')
endereco = input('Digite o seu Endereço: ')
cidade = input('Digite o sua cidade: ')
estado = input('Digite o seu estado: ')
cep = input('Digite o seu CEP: ')
telefone = input('Digite o seu telefone: ')
rg = input('Digite o seu RG: ')
nome_pai = input('Digite o nome do seu pai: ')
nome_mae = input('Digite o nome da sua mae: ')
escolaridade = input('Digite o grau de escolaridade: ')
print('=============================================')
print('==============================================')
print('==============CADASTRO DE CLIENTE ===========')
print(f'Nome: ',nome)
print(f'Sexo: ',sexo)
print(f'Endereço: ',endereco)
print(f'Cidade: ',cidade)
print(f'Estado: ',estado)
print(f'CEP: ',cep)
print(f'Telefone: ',telefone)
print(f'RG: ',rg)
print(f'Nome do pai: ',nome_pai)
print(f'Nome da mãe: ',nome_mae)
print(f'Escolaridade: ',escolaridade)
print('==============================================')
print('==============================================')
print('==============================================')